package us.sunrisemorning.mykancolle.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("basic", "member_id", Basic.class);
		// Composite Primary Key order: id,member_id
		arp.addMapping("deck", "id,member_id", Deck.class);
		// Composite Primary Key order: id,user
		arp.addMapping("furniture", "id,user", Furniture.class);
		arp.addMapping("incentive", "id", Incentive.class);
		// Composite Primary Key order: id,user
		arp.addMapping("kdock", "id,user", Kdock.class);
		arp.addMapping("log", "id", Log.class);
		// Composite Primary Key order: id,member_id
		arp.addMapping("material", "id,member_id", Material.class);
		// Composite Primary Key order: id,member_id
		arp.addMapping("ndock", "id,member_id", Ndock.class);
		arp.addMapping("params", "user", Params.class);
		// Composite Primary Key order: preset_no,user
		arp.addMapping("preset_deck", "preset_no,user", PresetDeck.class);
		// Composite Primary Key order: id,user
		arp.addMapping("ship", "id,user", Ship.class);
		// Composite Primary Key order: id,user
		arp.addMapping("slotitem", "id,user", Slotitem.class);
		// Composite Primary Key order: id,user
		arp.addMapping("useitem", "id,user", Useitem.class);
		arp.addMapping("user", "id", User.class);
	}
}

