package us.sunrisemorning.mykancolle.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		// Composite Primary Key order: id,user
		arp.addMapping("furniture", "id,user", Furniture.class);
		arp.addMapping("incentive", "id", Incentive.class);
		// Composite Primary Key order: id,user
		arp.addMapping("kdock", "id,user", Kdock.class);
		// Composite Primary Key order: id,user
		arp.addMapping("slotitem", "id,user", Slotitem.class);
		// Composite Primary Key order: id,user
		arp.addMapping("useitem", "id,user", Useitem.class);
		arp.addMapping("user", "id", User.class);
	}
}

