package us.sunrisemorning.mykancolle.model;

import com.alibaba.fastjson.annotation.JSONField;

import us.sunrisemorning.mykancolle.basemodel.BaseBasic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Basic extends BaseBasic<Basic> {
    public static final Basic dao = new Basic();

    public Integer[] getFurniture() {
        return new Integer[] { getFurniture1(), getFurniture2(), getFurniture3(), getFurniture4(), getFurniture5(), getFurniture6() };
    }

    public Integer[] getPvp() {
        // TODO:需要完成
        return new Integer[] { 0, 0 };
    }
    
    public Integer getMedals() {
        // TODO:需要完成
        return 10;
    }

    @JSONField(serialize = false)
    @Override
    public Integer getFurniture1() {
        return super.getFurniture1();
    }

    @JSONField(serialize = false)
    @Override
    public Integer getFurniture2() {
        return super.getFurniture2();
    }

    @JSONField(serialize = false)
    @Override
    public Integer getFurniture3() {
        return super.getFurniture3();
    }

    @JSONField(serialize = false)
    @Override
    public Integer getFurniture4() {
        return super.getFurniture4();
    }

    @JSONField(serialize = false)
    @Override
    public Integer getFurniture5() {
        return super.getFurniture5();
    }

    @JSONField(serialize = false)
    @Override
    public Integer getFurniture6() {
        return super.getFurniture6();
    }

}
