package us.sunrisemorning.mykancolle.model;

import com.alibaba.fastjson.annotation.JSONField;

import us.sunrisemorning.mykancolle.basemodel.BaseDeck;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Deck extends BaseDeck<Deck> {
    public static final Deck dao = new Deck();

    public Long[] getMission() {
        return new Long[] { getMission1(), getMission2(), getMission3(), getMission4() };
    }

    public Integer[] getShip() {
        return new Integer[] { getShip1(), getShip2(), getShip3(), getShip4(), getShip5(), getShip6() };
    }

    @JSONField(serialize = false)
    @Override
    public Long getMission1() {
        return super.getMission1();
    }

    @JSONField(serialize = false)
    @Override
    public Long getMission2() {
        return super.getMission2();
    }

    @JSONField(serialize = false)
    @Override
    public Long getMission3() {
        return super.getMission3();
    }

    @JSONField(serialize = false)
    @Override
    public Long getMission4() {
        return super.getMission4();
    }

    @JSONField(serialize = false)
    @Override
    public Integer getShip1() {
        return super.getShip1();
    }

    @JSONField(serialize = false)
    @Override
    public Integer getShip2() {
        return super.getShip2();
    }

    @JSONField(serialize = false)
    @Override
    public Integer getShip3() {
        return super.getShip3();
    }

    @JSONField(serialize = false)
    @Override
    public Integer getShip4() {
        return super.getShip4();
    }

    @JSONField(serialize = false)
    @Override
    public Integer getShip5() {
        return super.getShip5();
    }

    @JSONField(serialize = false)
    @Override
    public Integer getShip6() {
        return super.getShip6();
    }
}
