package us.sunrisemorning.mykancolle.model;

import us.sunrisemorning.mykancolle.basemodel.BaseFurniture;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Furniture extends BaseFurniture<Furniture> {
	public static final Furniture dao = new Furniture();
}
