package us.sunrisemorning.mykancolle.model;

import us.sunrisemorning.mykancolle.basemodel.BaseIncentive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Incentive extends BaseIncentive<Incentive> {
	public static final Incentive dao = new Incentive();
}
