package us.sunrisemorning.mykancolle.model;

import us.sunrisemorning.mykancolle.basemodel.BaseKdock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Kdock extends BaseKdock<Kdock> {
	public static final Kdock dao = new Kdock();
}
