package us.sunrisemorning.mykancolle.model;

import us.sunrisemorning.mykancolle.basemodel.BaseLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Log extends BaseLog<Log> {
    public static final Log dao = new Log();

    private int no = 1;

    public int getNo() {
        return no;
    }

    public void setNo(int no) {
        this.no = no;
    }

}
