package us.sunrisemorning.mykancolle.model;

import us.sunrisemorning.mykancolle.basemodel.BaseNdock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ndock extends BaseNdock<Ndock> {
	public static final Ndock dao = new Ndock();
}
