package us.sunrisemorning.mykancolle.model;

import us.sunrisemorning.mykancolle.basemodel.BaseParams;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Params extends BaseParams<Params> {
	public static final Params dao = new Params();
}
