package us.sunrisemorning.mykancolle.model;

import us.sunrisemorning.mykancolle.basemodel.BaseSlotitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Slotitem extends BaseSlotitem<Slotitem> {
	public static final Slotitem dao = new Slotitem();
}
