package us.sunrisemorning.mykancolle.model;

import us.sunrisemorning.mykancolle.basemodel.BaseUseitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Useitem extends BaseUseitem<Useitem> {
	public static final Useitem dao = new Useitem();
}
