package us.sunrisemorning.mykancolle.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShip<M extends BaseShip<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUser(java.lang.Long user) {
		set("user", user);
	}

	public java.lang.Long getUser() {
		return get("user");
	}

	public void setSortno(java.lang.Integer sortno) {
		set("sortno", sortno);
	}

	public java.lang.Integer getSortno() {
		return get("sortno");
	}

	public void setShip_id(java.lang.Integer ship_id) {
		set("ship_id", ship_id);
	}

	public java.lang.Integer getShip_id() {
		return get("ship_id");
	}

	public void setLv(java.lang.Integer lv) {
		set("lv", lv);
	}

	public java.lang.Integer getLv() {
		return get("lv");
	}

	public void setExp_total(java.lang.Integer exp_total) {
		set("exp_total", exp_total);
	}

	public java.lang.Integer getExp_total() {
		return get("exp_total");
	}

	public void setNowhp(java.lang.Integer nowhp) {
		set("nowhp", nowhp);
	}

	public java.lang.Integer getNowhp() {
		return get("nowhp");
	}

	public void setMaxhp(java.lang.Integer maxhp) {
		set("maxhp", maxhp);
	}

	public java.lang.Integer getMaxhp() {
		return get("maxhp");
	}

	public void setSlot1(java.lang.Integer slot1) {
		set("slot1", slot1);
	}

	public java.lang.Integer getSlot1() {
		return get("slot1");
	}

	public void setSlot2(java.lang.Integer slot2) {
		set("slot2", slot2);
	}

	public java.lang.Integer getSlot2() {
		return get("slot2");
	}

	public void setSlot3(java.lang.Integer slot3) {
		set("slot3", slot3);
	}

	public java.lang.Integer getSlot3() {
		return get("slot3");
	}

	public void setSlot4(java.lang.Integer slot4) {
		set("slot4", slot4);
	}

	public java.lang.Integer getSlot4() {
		return get("slot4");
	}

	public void setSlot5(java.lang.Integer slot5) {
		set("slot5", slot5);
	}

	public java.lang.Integer getSlot5() {
		return get("slot5");
	}

	public void setOnslot1(java.lang.Integer onslot1) {
		set("onslot1", onslot1);
	}

	public java.lang.Integer getOnslot1() {
		return get("onslot1");
	}

	public void setOnslot2(java.lang.Integer onslot2) {
		set("onslot2", onslot2);
	}

	public java.lang.Integer getOnslot2() {
		return get("onslot2");
	}

	public void setOnslot3(java.lang.Integer onslot3) {
		set("onslot3", onslot3);
	}

	public java.lang.Integer getOnslot3() {
		return get("onslot3");
	}

	public void setOnslot4(java.lang.Integer onslot4) {
		set("onslot4", onslot4);
	}

	public java.lang.Integer getOnslot4() {
		return get("onslot4");
	}

	public void setOnslot5(java.lang.Integer onslot5) {
		set("onslot5", onslot5);
	}

	public java.lang.Integer getOnslot5() {
		return get("onslot5");
	}

	public void setSlot_ex(java.lang.Integer slot_ex) {
		set("slot_ex", slot_ex);
	}

	public java.lang.Integer getSlot_ex() {
		return get("slot_ex");
	}

	public void setKyouka1(java.lang.Integer kyouka1) {
		set("kyouka1", kyouka1);
	}

	public java.lang.Integer getKyouka1() {
		return get("kyouka1");
	}

	public void setKyouka2(java.lang.Integer kyouka2) {
		set("kyouka2", kyouka2);
	}

	public java.lang.Integer getKyouka2() {
		return get("kyouka2");
	}

	public void setKyouka3(java.lang.Integer kyouka3) {
		set("kyouka3", kyouka3);
	}

	public java.lang.Integer getKyouka3() {
		return get("kyouka3");
	}

	public void setKyouka4(java.lang.Integer kyouka4) {
		set("kyouka4", kyouka4);
	}

	public java.lang.Integer getKyouka4() {
		return get("kyouka4");
	}

	public void setKyouka5(java.lang.Integer kyouka5) {
		set("kyouka5", kyouka5);
	}

	public java.lang.Integer getKyouka5() {
		return get("kyouka5");
	}

	public void setFuel(java.lang.Integer fuel) {
		set("fuel", fuel);
	}

	public java.lang.Integer getFuel() {
		return get("fuel");
	}

	public void setBull(java.lang.Integer bull) {
		set("bull", bull);
	}

	public java.lang.Integer getBull() {
		return get("bull");
	}

	public void setSlotnum(java.lang.Integer slotnum) {
		set("slotnum", slotnum);
	}

	public java.lang.Integer getSlotnum() {
		return get("slotnum");
	}

	public void setNdock_time(java.lang.Integer ndock_time) {
		set("ndock_time", ndock_time);
	}

	public java.lang.Integer getNdock_time() {
		return get("ndock_time");
	}

	public void setNdock_item1(java.lang.Integer ndock_item1) {
		set("ndock_item1", ndock_item1);
	}

	public java.lang.Integer getNdock_item1() {
		return get("ndock_item1");
	}

	public void setNdock_item2(java.lang.Integer ndock_item2) {
		set("ndock_item2", ndock_item2);
	}

	public java.lang.Integer getNdock_item2() {
		return get("ndock_item2");
	}

	public void setCond(java.lang.Integer cond) {
		set("cond", cond);
	}

	public java.lang.Integer getCond() {
		return get("cond");
	}

	public void setKaryoku1(java.lang.Integer karyoku1) {
		set("karyoku1", karyoku1);
	}

	public java.lang.Integer getKaryoku1() {
		return get("karyoku1");
	}

	public void setRaisou1(java.lang.Integer raisou1) {
		set("raisou1", raisou1);
	}

	public java.lang.Integer getRaisou1() {
		return get("raisou1");
	}

	public void setTaiku1(java.lang.Integer taiku1) {
		set("taiku1", taiku1);
	}

	public java.lang.Integer getTaiku1() {
		return get("taiku1");
	}

	public void setSoukou1(java.lang.Integer soukou1) {
		set("soukou1", soukou1);
	}

	public java.lang.Integer getSoukou1() {
		return get("soukou1");
	}

	public void setKaihi1(java.lang.Integer kaihi1) {
		set("kaihi1", kaihi1);
	}

	public java.lang.Integer getKaihi1() {
		return get("kaihi1");
	}

	public void setTaisen1(java.lang.Integer taisen1) {
		set("taisen1", taisen1);
	}

	public java.lang.Integer getTaisen1() {
		return get("taisen1");
	}

	public void setSakuteki1(java.lang.Integer sakuteki1) {
		set("sakuteki1", sakuteki1);
	}

	public java.lang.Integer getSakuteki1() {
		return get("sakuteki1");
	}

	public void setLucky1(java.lang.Integer lucky1) {
		set("lucky1", lucky1);
	}

	public java.lang.Integer getLucky1() {
		return get("lucky1");
	}

	public void setLocked(java.lang.Integer locked) {
		set("locked", locked);
	}

	public java.lang.Integer getLocked() {
		return get("locked");
	}

	public void setLocked_equip(java.lang.Integer locked_equip) {
		set("locked_equip", locked_equip);
	}

	public java.lang.Integer getLocked_equip() {
		return get("locked_equip");
	}

}
