package us.sunrisemorning.mykancolle.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMaterial<M extends BaseMaterial<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setMember_id(java.lang.Long member_id) {
		set("member_id", member_id);
	}

	public java.lang.Long getMember_id() {
		return get("member_id");
	}

	public void setValue(java.lang.Integer value) {
		set("value", value);
	}

	public java.lang.Integer getValue() {
		return get("value");
	}

}
