package us.sunrisemorning.mykancolle.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeck<M extends BaseDeck<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setMember_id(java.lang.Long member_id) {
		set("member_id", member_id);
	}

	public java.lang.Long getMember_id() {
		return get("member_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setName_id(java.lang.String name_id) {
		set("name_id", name_id);
	}

	public java.lang.String getName_id() {
		return get("name_id");
	}

	public void setFlagship(java.lang.String flagship) {
		set("flagship", flagship);
	}

	public java.lang.String getFlagship() {
		return get("flagship");
	}

	public void setMission1(java.lang.Long mission1) {
		set("mission1", mission1);
	}

	public java.lang.Long getMission1() {
		return get("mission1");
	}

	public void setMission2(java.lang.Long mission2) {
		set("mission2", mission2);
	}

	public java.lang.Long getMission2() {
		return get("mission2");
	}

	public void setMission3(java.lang.Long mission3) {
		set("mission3", mission3);
	}

	public java.lang.Long getMission3() {
		return get("mission3");
	}

	public void setMission4(java.lang.Long mission4) {
		set("mission4", mission4);
	}

	public java.lang.Long getMission4() {
		return get("mission4");
	}

	public void setShip1(java.lang.Integer ship1) {
		set("ship1", ship1);
	}

	public java.lang.Integer getShip1() {
		return get("ship1");
	}

	public void setShip2(java.lang.Integer ship2) {
		set("ship2", ship2);
	}

	public java.lang.Integer getShip2() {
		return get("ship2");
	}

	public void setShip3(java.lang.Integer ship3) {
		set("ship3", ship3);
	}

	public java.lang.Integer getShip3() {
		return get("ship3");
	}

	public void setShip4(java.lang.Integer ship4) {
		set("ship4", ship4);
	}

	public java.lang.Integer getShip4() {
		return get("ship4");
	}

	public void setShip5(java.lang.Integer ship5) {
		set("ship5", ship5);
	}

	public java.lang.Integer getShip5() {
		return get("ship5");
	}

	public void setShip6(java.lang.Integer ship6) {
		set("ship6", ship6);
	}

	public java.lang.Integer getShip6() {
		return get("ship6");
	}

}
