package us.sunrisemorning.mykancolle.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSlotitem<M extends BaseSlotitem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUser(java.lang.Long user) {
		set("user", user);
	}

	public java.lang.Long getUser() {
		return get("user");
	}

	public void setSlotitem_id(java.lang.Integer slotitem_id) {
		set("slotitem_id", slotitem_id);
	}

	public java.lang.Integer getSlotitem_id() {
		return get("slotitem_id");
	}

	public void setLocked(java.lang.Integer locked) {
		set("locked", locked);
	}

	public java.lang.Integer getLocked() {
		return get("locked");
	}

	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}

	public java.lang.Integer getLevel() {
		return get("level");
	}

	public void setAlv(java.lang.Integer alv) {
		set("alv", alv);
	}

	public java.lang.Integer getAlv() {
		return get("alv");
	}

}
