package us.sunrisemorning.mykancolle.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePresetDeck<M extends BasePresetDeck<M>> extends Model<M> implements IBean {

	public void setPreset_no(java.lang.Long preset_no) {
		set("preset_no", preset_no);
	}

	public java.lang.Long getPreset_no() {
		return get("preset_no");
	}

	public void setUser(java.lang.Long user) {
		set("user", user);
	}

	public java.lang.Long getUser() {
		return get("user");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setName_id(java.lang.String name_id) {
		set("name_id", name_id);
	}

	public java.lang.String getName_id() {
		return get("name_id");
	}

	public void setShip1(java.lang.Long ship1) {
		set("ship1", ship1);
	}

	public java.lang.Long getShip1() {
		return get("ship1");
	}

	public void setShip2(java.lang.Long ship2) {
		set("ship2", ship2);
	}

	public java.lang.Long getShip2() {
		return get("ship2");
	}

	public void setShip3(java.lang.Long ship3) {
		set("ship3", ship3);
	}

	public java.lang.Long getShip3() {
		return get("ship3");
	}

	public void setShip4(java.lang.Long ship4) {
		set("ship4", ship4);
	}

	public java.lang.Long getShip4() {
		return get("ship4");
	}

	public void setShip5(java.lang.Long ship5) {
		set("ship5", ship5);
	}

	public java.lang.Long getShip5() {
		return get("ship5");
	}

	public void setShip6(java.lang.Long ship6) {
		set("ship6", ship6);
	}

	public java.lang.Long getShip6() {
		return get("ship6");
	}

}
