package us.sunrisemorning.mykancolle.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBasic<M extends BaseBasic<M>> extends Model<M> implements IBean {

	public void setMember_id(java.lang.Long member_id) {
		set("member_id", member_id);
	}

	public java.lang.Long getMember_id() {
		return get("member_id");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public void setNickname_id(java.lang.String nickname_id) {
		set("nickname_id", nickname_id);
	}

	public java.lang.String getNickname_id() {
		return get("nickname_id");
	}

	public void setActive_flag(java.lang.Integer active_flag) {
		set("active_flag", active_flag);
	}

	public java.lang.Integer getActive_flag() {
		return get("active_flag");
	}

	public void setStarttime(java.lang.Long starttime) {
		set("starttime", starttime);
	}

	public java.lang.Long getStarttime() {
		return get("starttime");
	}

	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}

	public java.lang.Integer getLevel() {
		return get("level");
	}

	public void setRank(java.lang.Integer rank) {
		set("rank", rank);
	}

	public java.lang.Integer getRank() {
		return get("rank");
	}

	public void setExperience(java.lang.Integer experience) {
		set("experience", experience);
	}

	public java.lang.Integer getExperience() {
		return get("experience");
	}

	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}

	public java.lang.String getComment() {
		return get("comment");
	}

	public void setComment_id(java.lang.String comment_id) {
		set("comment_id", comment_id);
	}

	public java.lang.String getComment_id() {
		return get("comment_id");
	}

	public void setMax_chara(java.lang.Integer max_chara) {
		set("max_chara", max_chara);
	}

	public java.lang.Integer getMax_chara() {
		return get("max_chara");
	}

	public void setMax_slotitem(java.lang.Integer max_slotitem) {
		set("max_slotitem", max_slotitem);
	}

	public java.lang.Integer getMax_slotitem() {
		return get("max_slotitem");
	}

	public void setMax_kagu(java.lang.Integer max_kagu) {
		set("max_kagu", max_kagu);
	}

	public java.lang.Integer getMax_kagu() {
		return get("max_kagu");
	}

	public void setPlaytime(java.lang.Integer playtime) {
		set("playtime", playtime);
	}

	public java.lang.Integer getPlaytime() {
		return get("playtime");
	}

	public void setTutorial(java.lang.Integer tutorial) {
		set("tutorial", tutorial);
	}

	public java.lang.Integer getTutorial() {
		return get("tutorial");
	}

	public void setFurniture1(java.lang.Integer furniture1) {
		set("furniture1", furniture1);
	}

	public java.lang.Integer getFurniture1() {
		return get("furniture1");
	}

	public void setFurniture2(java.lang.Integer furniture2) {
		set("furniture2", furniture2);
	}

	public java.lang.Integer getFurniture2() {
		return get("furniture2");
	}

	public void setFurniture3(java.lang.Integer furniture3) {
		set("furniture3", furniture3);
	}

	public java.lang.Integer getFurniture3() {
		return get("furniture3");
	}

	public void setFurniture4(java.lang.Integer furniture4) {
		set("furniture4", furniture4);
	}

	public java.lang.Integer getFurniture4() {
		return get("furniture4");
	}

	public void setFurniture5(java.lang.Integer furniture5) {
		set("furniture5", furniture5);
	}

	public java.lang.Integer getFurniture5() {
		return get("furniture5");
	}

	public void setFurniture6(java.lang.Integer furniture6) {
		set("furniture6", furniture6);
	}

	public java.lang.Integer getFurniture6() {
		return get("furniture6");
	}

	public void setCount_deck(java.lang.Integer count_deck) {
		set("count_deck", count_deck);
	}

	public java.lang.Integer getCount_deck() {
		return get("count_deck");
	}

	public void setCount_kdock(java.lang.Integer count_kdock) {
		set("count_kdock", count_kdock);
	}

	public java.lang.Integer getCount_kdock() {
		return get("count_kdock");
	}

	public void setCount_ndock(java.lang.Integer count_ndock) {
		set("count_ndock", count_ndock);
	}

	public java.lang.Integer getCount_ndock() {
		return get("count_ndock");
	}

	public void setFcoin(java.lang.Integer fcoin) {
		set("fcoin", fcoin);
	}

	public java.lang.Integer getFcoin() {
		return get("fcoin");
	}

	public void setSt_win(java.lang.Integer st_win) {
		set("st_win", st_win);
	}

	public java.lang.Integer getSt_win() {
		return get("st_win");
	}

	public void setSt_lose(java.lang.Integer st_lose) {
		set("st_lose", st_lose);
	}

	public java.lang.Integer getSt_lose() {
		return get("st_lose");
	}

	public void setMs_count(java.lang.Integer ms_count) {
		set("ms_count", ms_count);
	}

	public java.lang.Integer getMs_count() {
		return get("ms_count");
	}

	public void setMs_success(java.lang.Integer ms_success) {
		set("ms_success", ms_success);
	}

	public java.lang.Integer getMs_success() {
		return get("ms_success");
	}

	public void setPt_win(java.lang.Integer pt_win) {
		set("pt_win", pt_win);
	}

	public java.lang.Integer getPt_win() {
		return get("pt_win");
	}

	public void setPt_lose(java.lang.Integer pt_lose) {
		set("pt_lose", pt_lose);
	}

	public java.lang.Integer getPt_lose() {
		return get("pt_lose");
	}

	public void setPt_challenged(java.lang.Integer pt_challenged) {
		set("pt_challenged", pt_challenged);
	}

	public java.lang.Integer getPt_challenged() {
		return get("pt_challenged");
	}

	public void setPt_challenged_win(java.lang.Integer pt_challenged_win) {
		set("pt_challenged_win", pt_challenged_win);
	}

	public java.lang.Integer getPt_challenged_win() {
		return get("pt_challenged_win");
	}

	public void setFirstflag(java.lang.Integer firstflag) {
		set("firstflag", firstflag);
	}

	public java.lang.Integer getFirstflag() {
		return get("firstflag");
	}

	public void setTutorial_progress(java.lang.Integer tutorial_progress) {
		set("tutorial_progress", tutorial_progress);
	}

	public java.lang.Integer getTutorial_progress() {
		return get("tutorial_progress");
	}

	public void setLarge_dock(java.lang.Integer large_dock) {
		set("large_dock", large_dock);
	}

	public java.lang.Integer getLarge_dock() {
		return get("large_dock");
	}

}
