package us.sunrisemorning.mykancolle.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIncentive<M extends BaseIncentive<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUser(java.lang.Long user) {
		set("user", user);
	}

	public java.lang.Long getUser() {
		return get("user");
	}

	public void setMode(java.lang.Integer mode) {
		set("mode", mode);
	}

	public java.lang.Integer getMode() {
		return get("mode");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setMst_id(java.lang.Integer mst_id) {
		set("mst_id", mst_id);
	}

	public java.lang.Integer getMst_id() {
		return get("mst_id");
	}

	public void setGetmes(java.lang.String getmes) {
		set("getmes", getmes);
	}

	public java.lang.String getGetmes() {
		return get("getmes");
	}

}
